scenarios:
  bench1:
    zstor_config:
      namespace: adisk
      datastor:
        shards:
          - 127.0.0.1:45627
          - 127.0.0.1:49861
          - 127.0.0.1:37355
      metastor:
          shards:
            - 127.0.0.1:51583
            - 127.0.0.1:48843
          encryption:
            private_key: ab345678901234567890123456789012
      pipeline:
        block_size: 4096
        compression:
          mode: default
        encryption:
          private_key: ab345678901234567890123456789012
        distribution:
          data_shards: 2
          parity_shards: 1
    bench_config:
      method: write
      result_output: per_second
      duration: 5
      operations: 0
      key_size: 48
      value_size: 128
      clients: 1
